language: python
python:
  - "3.5"

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
  - pip install cactus
  - pip install html5validator
  - nvm install 6.10.3
  - nvm use 6.10.3
  - npm install -g yarn
  - yarn install

script:
  - cactus build
  - html5validator --root .build --show-warnings
