language: python
python:
  - "3.6"

# Work around for boto bug:
# https://github.com/boto/boto/issues/3717#issuecomment-430894557
env:
  - BOTO_CONFIG=/dev/null

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-set-default

install:
  - pip install -r requirements.txt
  - pip install html5validator

script:
  - cactus build
  - html5validator --root .build --show-warnings --also-check-css
