name: Build site and check output

on:
  push:
    branches:
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build site
      run: |
        cactus build

    - name: Check html
      uses: Cyb3r-Jak3/html5validator-action@v0.4.2
      with:
        root: .build/
        css: true
        log_level: INFO

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .build
        publish_branch: master
        force_orphan: true
