name: Build site and check output

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install openjdk
      run: |
        sudo apt-get install openjdk-8-jre
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Build site
      run: |
        cactus build
    - name: Check html
      run: |
        html5validator --root .build --show-warnings --also-check-css

